improved testing

diff --git a/s/test-util/expecting b/s/test-util/expecting
--- a/s/test-util/expecting
+++ b/s/test-util/expecting
@@ -7,26 +7,19 @@ expect_exit_code() {
     expected_retval=$1
     shift
 
+    echo -en "\033[37m[${BASH_SOURCE[0]#*kissbash/}] \033[33m" >&2
+    echo "bash -c \"$*\"" >&2
+    echo -e "\033[0m" >&2
+
     tmpf=`mktemp`
-
-    echo -en "\033[37m[${BASH_SOURCE[0]#*kissbash/}] \033[33m" >> $tmpf
-    #echo "bash -c \"$* >> $tmpf 2>&1\"" >> $tmpf
-    echo "bash -c \"$*\"" >> $tmpf
-    echo -e "\033[0m" >> $tmpf
-
     bash -c "$* >> $tmpf 2>&1" # HERE
     retval=$?
 
-    echo >> $tmpf
-    echo -e "\033[37m[${BASH_SOURCE[0]#*kissbash/}] \033[33mexpecting exit code "$expected_retval", got "$retval"\033[0m" >> $tmpf
+    cat $tmpf >&2
+    rm $tmpf
 
-    cat $tmpf
-    #rm $tmpf
+    echo >&2
+    echo -e "\033[37m[${BASH_SOURCE[0]#*kissbash/}] \033[33mexpecting exit code "$expected_retval", got "$retval"\033[0m" >&2
 
-    echo -en "\033[1A\033[0G" >&2
-    if [ "x$retval" == "x$expected_retval" ]; then
-        echo -e "\033[32mPASS\033[0m" >&2
-    else
-        echo -e "\033[31mFAIL\033[0m" >&2
-    fi
+    return $retval
 }
diff --git a/t/test-all b/t/test-all
--- a/t/test-all
+++ b/t/test-all
@@ -1,6 +1,6 @@
 DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
 
-all_stdout=`mktemp`
+stdout_stderr=`mktemp`
 
 for f in `find $DIR -type f`; do
     self=`basename $f`
@@ -8,19 +8,27 @@ for f in `find $DIR -type f`; do
         continue
     fi
 
-    echo -e "\033[35m================================================================================\033[0m" >> $all_stdout
-    echo -e "\033[37m[${BASH_SOURCE[0]#*kissbash/}] \033[33m${f#*kissbash/}\033[0m" >> $all_stdout
+    echo -e "\033[35m================================================================================\033[0m" >> $stdout_stderr
+    echo -e "\033[37m[${BASH_SOURCE[0]#*kissbash/}] \033[33m${f#*kissbash/}\033[0m" >> $stdout_stderr
     echo -e "\033[37mRunning $f\033[0m" >&2
 
     (
         . $f
         cat "$f" | grep -E '^test_[_a-zA-Z]*()' | while read line; do
-            echo -e "\033[37m--------------------------------------------------------------------------------\033[0m" >> $all_stdout
-            func=${line%()*}
-            echo -e "\033[37m[${BASH_SOURCE[0]#*kissbash/}] \033[33m${f#*kissbash/}::\033[1;33m$func\033[0m" >> $all_stdout
-            echo -e "     \033[37m$func\033[0m \033[s" >&2
-            "$func" >> $all_stdout
-            echo >> $all_stdout
+            echo -e "\033[37m--------------------------------------------------------------------------------\033[0m" >> $stdout_stderr
+            test_func=${line%()*}
+            echo -e "\033[37m[${BASH_SOURCE[0]#*kissbash/}] \033[33m${f#*kissbash/}::\033[1;33m$test_func\033[0m" >> $stdout_stderr
+            echo -e "     \033[37m$test_func\033[0m \033[s" >&2
+            "$test_func" >> $stdout_stderr 2>&1
+            retval=$?
+
+            echo -en "\033[1A\033[0G" >&2
+            if [ "x$retval" == "x$expected_retval" ]; then
+                echo -e "\033[32mPASS\033[0m" >&2
+            else
+                echo -e "\033[31mFAIL\033[0m" >&2
+            fi
+            echo >> $stdout_stderr
         done
     )
 
@@ -29,9 +37,9 @@ done
 
 echo -e "\033[36m**************************************DONE**************************************\033[0m\n"
 
-echo -e "for details,\n\033[1mcat $all_stdout\033[0m"
+echo -e "for details,\n\033[1mcat $stdout_stderr\033[0m"
 
 if [ "x$1" == "x-v" ] || [ "x$1" == "x--verbose" ]; then
     echo
-    cat $all_stdout
+    cat $stdout_stderr
 fi
